services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ohmiesdb
      POSTGRES_USER: ohmies
      POSTGRES_PASSWORD: Pass1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
